[data.instance.packages.config]
template_dir = "${XDG_DATA_HOME}/chezmoi/resources/templates"

[data.instance.packages.config.mamba]
environments = [
  "clx"
]

[data.instance.packages.config.sdkman]
java_distros = [
  "Corretto"
]
