[packages.linux.ubuntu.server]
apt = [
  "bat",
  "btop",
  "build-essential",
  "direnv",
  "eza",
  "fd-find",
  "fzf",
  "openssh-server",
  "nvim",
  "ripgrep",
  "shellcheck",
  "yq",
  "zoxide",
  "zsh"
]
snap = [ ]
snap-classic = [
  "aws-cli" 
]

[packages.linux.ubuntu.desktop]
apt = [
  "bat",
  "btop",
  "build-essential",
  "direnv",
  "eza",
  "fd-find",
  "fzf",
  "openssh-server",
  "nvim",
  "ripgrep",
  "shellcheck",
  "yq",
  "zoxide",
  "zsh"
]
snap = [
  "vivaldi"
]
snap-classic = [
  "aws-cli"
]
