# Use .chezmoidata/instance-options.toml to enable specific-case or ephemeral
# settings without chezmoi management or source control


[instance.options]
# include-zshrc = ["docker-postgis"]
# include-zshrc = ["julia"]

docker-postgis = [
  "# -- postgis-docker",
  "alias depg='docker exec -it postgis /bin/bash'",
  "alias dspg='docker start postgis'",
  "alias dxpg='docker stop postgis'"
]

gcloud = [
  "# -- gcloud",
  "alias gcdev='gcloud config set project dev'",
  "alias gcstg='gcloud config set project stg'",
  "alias gcprd='gcloud config set project prd'"
]

julia = [
  "# -- julia",
  '''alias jd='julia --startup-file=no -e "using DaemonMode; serve()"'''',
  '''alias jc='julia --startup-file=no -e "using DaemonMode; runargs()"''''
]

serial-console = [
  "# -- serial-console",
  "alias s96='screen /dev/ttyUSB0 9600'",
  "alias s115='screen /dev/ttyUSB0 115200'"
]

ubuntu-tegra = [
  "# -- TODO: tegra oddity",
  "unset LESS",
]
